[package]
name = "ftp_server"
version = "0.1.0"
authors = ["Nathan GUIGUI <nathan.guigui@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.4"
getopts = "0.2"